kind: ClusterRole
{{- if .Capabilities.APIVersions.Has "rbac.authorization.k8s.io/v1" }}
apiVersion: rbac.authorization.k8s.io/v1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- end }}
metadata:
  name: {{ include "prometheus-kubernetes-events-exporter.fullname" . }}
  labels:
{{ include "prometheus-kubernetes-events-exporter.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
