apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-kubernetes-events-exporter.fullname" . }}
  labels:
{{ include "prometheus-kubernetes-events-exporter.labels" . | indent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9102"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: 9102
    targetPort: 9102
  selector:
    app.kubernetes.io/name: {{ include "prometheus-kubernetes-events-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
